name: ispark-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26
  - pandas=1.5.3
  - shapely=2.0.6
  - geopandas=0.14.*
  - gdal
  - rasterio
  - fiona
  - rioxarray
  - xarray<=2023.12.0
  - scikit-learn
  - matplotlib
  - geemap
  - earthengine-api
  - h5py
  - xlsxwriter
  - google-colab
  - pip
  - pip:
      - torch==2.2.1
      - torchvision==0.17.1
      - torchmetrics==1.3.2
      - wandb==0.16.3
